version: "3.7"
services:

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION:-7.2}
        - XDEBUG=${XDEBUG:-0}
    volumes:
      - ./:/docker
    environment:
        - TRAVIS
        - TRAVIS_JOB_ID
        - TRAVIS_BRANCH
        - TRAVIS_PULL_REQUEST
